-- DataPilot: PostgreSQL schema for the fictional e-commerce store.
--
-- Six tables:
--   customers ──< orders ──< order_items >── products >── categories
--                   │
--                   └──< payments
--
-- Business rules used by the metrics in PROJECT.md:
--   Completed Order    = orders.status = 'delivered'
--   Successful Payment = payments.status = 'completed'
--   Revenue            = SUM(order_items.quantity * order_items.unit_price) for completed orders
--   Profit             = SUM(order_items.quantity * (order_items.unit_price - order_items.unit_cost)) for completed orders
--   Average Order Value = Revenue / COUNT(DISTINCT completed orders)
--
-- This script is re-runnable: it drops and recreates all six tables.
-- WARNING: running it deletes all existing data in these tables.

BEGIN;

DROP TABLE IF EXISTS payments, order_items, orders, products, categories, customers;


-- People who shop at the store.
CREATE TABLE customers (
    customer_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    full_name    TEXT NOT NULL,
    email        TEXT NOT NULL UNIQUE,
    city         TEXT NOT NULL,
    state        TEXT NOT NULL,
    country      TEXT NOT NULL,
    signup_date  DATE NOT NULL
);


-- Product categories, e.g. Electronics, Apparel, Home.
CREATE TABLE categories (
    category_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         TEXT NOT NULL UNIQUE
);


-- Items for sale. price and cost are the CURRENT selling price and per-unit cost.
-- Historical revenue and profit use the values captured in order_items, not these.
CREATE TABLE products (
    product_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category_id     INTEGER NOT NULL REFERENCES categories (category_id) ON DELETE RESTRICT,
    name            TEXT NOT NULL,
    price           NUMERIC(10, 2) NOT NULL CHECK (price >= 0),
    cost            NUMERIC(10, 2) NOT NULL CHECK (cost >= 0),
    stock_quantity  INTEGER NOT NULL CHECK (stock_quantity >= 0)
);


-- A purchase by a customer. Only 'delivered' orders count as completed.
CREATE TABLE orders (
    order_id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id  INTEGER NOT NULL REFERENCES customers (customer_id) ON DELETE RESTRICT,
    order_date   DATE NOT NULL,
    status       TEXT NOT NULL
                 CHECK (status IN ('pending', 'shipped', 'delivered', 'cancelled', 'returned'))
);


-- Line items in an order. unit_price and unit_cost are captured at the time of the order,
-- so historical revenue and profit stay correct if products.price or products.cost change later.
CREATE TABLE order_items (
    order_item_id  INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id       INTEGER NOT NULL REFERENCES orders (order_id) ON DELETE CASCADE,
    product_id     INTEGER NOT NULL REFERENCES products (product_id) ON DELETE RESTRICT,
    quantity       INTEGER NOT NULL CHECK (quantity > 0),
    unit_price     NUMERIC(10, 2) NOT NULL CHECK (unit_price >= 0),
    unit_cost      NUMERIC(10, 2) NOT NULL CHECK (unit_cost >= 0),
    UNIQUE (order_id, product_id)
);


-- Payment attempts and refunds for orders. Only 'completed' payments are successful.
CREATE TABLE payments (
    payment_id      INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id        INTEGER NOT NULL REFERENCES orders (order_id) ON DELETE CASCADE,
    payment_date    DATE NOT NULL,
    amount          NUMERIC(10, 2) NOT NULL CHECK (amount >= 0),
    payment_method  TEXT NOT NULL
                    CHECK (payment_method IN ('credit_card', 'debit_card', 'upi', 'net_banking', 'wallet', 'cash_on_delivery')),
    status          TEXT NOT NULL
                    CHECK (status IN ('pending', 'completed', 'failed', 'refunded'))
);


-- Indexes on foreign keys and dates used for joins, grouping and time filters.
-- (order_items.order_id is already covered by the UNIQUE (order_id, product_id) index.)
CREATE INDEX idx_products_category_id   ON products (category_id);
CREATE INDEX idx_orders_customer_id     ON orders (customer_id);
CREATE INDEX idx_orders_order_date      ON orders (order_date);
CREATE INDEX idx_order_items_product_id ON order_items (product_id);
CREATE INDEX idx_payments_order_id      ON payments (order_id);

COMMIT;
